### PR TITLE
Lycidas0815 vstemplate

### PR DESCRIPTION
**Pull request by Lycidas0815**
I have added a Visual Studio template based on your project and adapted the readme accordingly. It was dead simple so you might want to have a look at the description and merge it to you master branch.

Greetings,
Ly

### CODE REVIEW

**Comment by cosmo0** [comment]
Awesome thanks ! I'll check it out and try to create an automatic build of it :smile:

**Comment by cosmo0** [comment]
Thank you so much ! I was able to write a script to automate the generation and installation of the template :smile: :+1:

**Comment by Lycidas0815** [comment]
Glad I could help you. Had a look at your script, that's awesome too, thanks for your effort. 

One thing I noticed: if you generate the project template using VS, you don't have to replace the namespaces with $safeprojectname. They are adapted based on the project name you choose while creating the new project. So maybe you could take out that step in your generating ps file.

On a sidenote: the usage of $safeprojectname leads to a non-compilable solution file which is kind of sad if you do not want the template explicitly.

Greetings,
Ly

**Comment by cosmo0** [comment]
Yeah, but I like both the ability to build and test the template, and that the user just has to double-click on a batch file to install.

It's just missing the automatic creation of the vstemplate file but for now I think it's a bit overkill.

**Pull request merged**
